name: pyotpes

channels:
  - default
  
dependencies:
  - python=3.7.6
  - numba=0.48.0
  - numpy=1.18.1
  - scipy=1.4.1
~                                                                                                                                                                     
~                                                                                                                                                                     
~                                                                                                                                                                     
~                                                                                                                                                                     
-- INSERT --
