name: bo
channels:
  - conda-forge
  - acellera  # channel for ax-platform
dependencies:
  - python
  - matplotlib
  - numpy=1.19  # fixed for pyoptes
  - scipy
  - numba=0.48  # fixed for pyoptes
  - networkx
  - tqdm
  - cma
#  - gfortran
  - pytorch
  - pip
  - pip:
#    - git+https://github.com/uber-research/TuRBO
#    - dragonfly-opt == 0.1.4
    - smac==0.11.1
    - ax-platform>=0.1.17
    - pymoo