name: bbo
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python
  - matplotlib
  - numpy=1.21  # fixed for pyoptes
  - scipy
  - numba=0.55  # fixed for pyoptes
  - networkx
  - tqdm
  - cma=3.0.3
  - pytorch-gpu
  - pytorch # needed for pytorch-geometric and -scatter to work properly
  - cudatoolkit
  - torchvision
  - jupyter
  - ipykernel
  - pip
  - pandas
  - pyg
  - torch-scatter
  - pip:
    - pyGPGO