name: bbo
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - matplotlib
  - numpy=1.19  # fixed for pyoptes
  - scipy
  - numba=0.48  # fixed for pyoptes
  - networkx
  - tqdm
  - cma=3.0.3
  - pytorch-gpu
  - cudatoolkit=10.1
  - torchvision
  - jupyter
  - ipykernel
  - pip
  - pandas
  - pip:
    - pyGPGO